package io.vertigo.ai.llm.model;

import java.util.function.Consumer;

public interface VLlmMessageStream<R> {

	/**
	 * Invoked each time the language model generates a new token in a textual response.
	 *
	 * @param tokenHandler Send the newly generated token, which is a part of the complete response.
	 * @param messageHandler Send the current full message (which contains all tokens generated so far) after a new token is issued.
	 */
	VLlmMessageStream<R> onUpdate(Consumer<String> tokenHandler, Consumer<R> messageHandler);

	/**
	 * Invoked when the language model has finished streaming a response.
	 *
	 * @param response Send the complete response generated by the language model.
	 */
	VLlmMessageStream<R> onComplete(final Consumer<R> messageHandler);

	/**
	 * This method is invoked when an error occurs during streaming.
	 *
	 * @param errorHandler lambda that will be invoked when an error occurs
	 */
	VLlmMessageStream<R> onError(Consumer<Throwable> errorHandler);

	/**
	 * Completes the current token stream building and starts processing.
	 * Will send a request to LLM and start response streaming.
	 */
	void start();
}
