<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.vertigo</groupId>
		<artifactId>vertigo-parent</artifactId>
		<version>4.3.2</version>
	</parent>

	<artifactId>vertigo-ai</artifactId>
	<packaging>jar</packaging>
	<name>vertigo-ai</name>
	<version>4.3.2-SNAPSHOT</version>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.vertigo</groupId>
				<artifactId>vertigo-vega</artifactId>
				<version>${vertigo.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-core</artifactId>
			<version>${vertigo.version}</version>
		</dependency>
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-commons</artifactId>
			<version>${vertigo.version}</version>
		</dependency>
		
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-datastore</artifactId>
			<version>${vertigo.version}</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-datafactory</artifactId>
			<version>${vertigo.version}</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-vega</artifactId>
			<version>${vertigo.version}</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-redis-connector</artifactId>
			<version>${vertigo.version}</version>
			<optional>true</optional>
		</dependency>
		
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
	</dependencies>
</project>
